# docker-compose.yml
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rest_api_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PHX_HOST=13.232.8.252
      - SECRET_KEY_BASE=+ATD3ZQ4bcd9OVcZgtGINhlK32Q23zl+qIgFE946U9sN63FEsIxeKIjE0++qRWiu
      - DATABASE_URL=ecto://postgres:postgres@db:5432/rest_api_prod
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: